preset: psr2

enabled:
  - concat_with_spaces
  - function_typehint_space
  - hash_to_slash_comment
  - lowercase_cast
  - native_function_casing
  - no_alias_functions
  - no_blank_lines_after_phpdoc
  - no_empty_statement
  - no_extra_consecutive_blank_lines
  - no_leading_import_slash
  - no_leading_namespace_whitespace
  - no_short_bool_cast
  - no_singleline_whitespace_before_semicolons
  - no_trailing_comma_in_singleline_array
  - no_unneeded_control_parentheses
  - no_unused_imports
  - no_whitespace_in_blank_line
  - ordered_imports
  - phpdoc_no_package
  - phpdoc_scalar
  - single_quote
  - self_accessor
  - short_array_syntax
  - whitespace_after_comma_in_array

finder:
  name:
    - "*.php"
  exclude:
    - ".Build"
    - "Documentation"
    - "Resources"
  not-name:
    - "ext_emconf.php"
