# .travis.yml
language: php

sudo: false

php:
  - 7.2

matrix:
  fast_finish: true

addons:
  apt:
    packages:
      - parallel
cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer require typo3/minimal:${TYPO3_VERSION} typo3/cms-lowlevel:${TYPO3_VERSION} typo3/cms-about:${TYPO3_VERSION} typo3/cms-belog:${TYPO3_VERSION} typo3/cms-beuser:${TYPO3_VERSION} typo3/cms-felogin:${TYPO3_VERSION} typo3/cms-fluid-styled-content:${TYPO3_VERSION} typo3/cms-form:${TYPO3_VERSION} typo3/cms-impexp:${TYPO3_VERSION} typo3/cms-info:${TYPO3_VERSION} typo3/cms-rte-ckeditor:${TYPO3_VERSION} typo3/cms-setup:${TYPO3_VERSION} typo3/cms-seo:${TYPO3_VERSION} typo3/cms-sys-note:${TYPO3_VERSION} typo3/cms-t3editor:${TYPO3_VERSION} typo3/cms-tstemplate:${TYPO3_VERSION} typo3/cms-viewpage:${TYPO3_VERSION} typo3/cms-adminpanel:${TYPO3_VERSION} typo3/cms-redirects:${TYPO3_VERSION} typo3/cms-workspaces:${TYPO3_VERSION} typo3/cms-reports:${TYPO3_VERSION} typo3/cms-scheduler:${TYPO3_VERSION} typo3/cms-recycler:${TYPO3_VERSION} typo3/cms-opendocs:${TYPO3_VERSION} typo3/cms-linkvalidator:${TYPO3_VERSION}

  - git checkout composer.json
  - export TYPO3_PATH_WEB="$PWD/.Build/web"

script:
  - >
    if [ -d "Tests/Unit" ]; then
      echo;
      echo "Running unit tests";
      echo;
      echo;
      .Build/bin/phpunit Tests/Unit/;
    fi
  - >
    echo;
    echo "Running php lint";
    echo;
    echo;
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;;

after_script:
  - .Build/bin/php-coveralls -v

jobs:
  allow_failures:
    - env: TYPO3_VERSION=dev-master
  include:
    - stage: test
      php: 7.2
      env: TYPO3_VERSION=9.5.0
    - stage: test
      php: 7.2
      env: TYPO3_VERSION=9.5.1
    - stage: test
      php: 7.2
      env: TYPO3_VERSION=9.5.2
    - stage: test
      php: 7.2
      env: TYPO3_VERSION=9.5.3
    - stage: test
      php: 7.2
      env: TYPO3_VERSION=9.5.4
    - stage: test
      php: 7.2
      env: TYPO3_VERSION=9.5.5
    - stage: test
      php: 7.2
      env: TYPO3_VERSION=9.5.6
    - stage: test
      php: 7.2
      env: TYPO3_VERSION=9.5.7
    - stage: test
      php: 7.2
      env: TYPO3_VERSION=dev-master
