name: Unit tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ci:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        typo3_version:
          - 10.4.20
          - 10.4.21
#          - 10.4.22
#          - 10.4.23
#          - 10.4.24
#          - 10.4.25
#          - 10.4.26
#          - 10.4.27
#          - 10.4.28
#          - 11.5.0
#          - 11.5.1
#          - 11.5.2
#          - 11.5.3
#          - 11.5.4
#          - 11.5.5
#          - 11.5.6
#          - 11.5.7
#          - 11.5.8
#          - 11.5.9
#          - 11.5.10
#          - dev-master

    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP Version
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.2
          tools: composer:v1

      # Directory permissions for .composer are wrong, so we remove the complete directory
      # https://github.com/actions/virtual-environments/issues/824
#      - name: Delete .composer directory
#        run: sudo rm -rf ~/.composer
      - name: Validate composer.json
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: .Build/vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}-${{ matrix.typo3_version }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.typo3_version }}-

      - name: Install dependencies for TYPO3 version "${{ matrix.typo3_version }}"
        run: composer require typo3/cms-backend:${{ matrix.typo3_version }} typo3/cms-core:${{ matrix.typo3_version }} typo3/cms-extbase:${{ matrix.typo3_version }} typo3/cms-extensionmanager:${{ matrix.typo3_version }} typo3/cms-filelist:${{ matrix.typo3_version }} typo3/cms-fluid:${{ matrix.typo3_version }} typo3/cms-frontend:${{ matrix.typo3_version }} typo3/cms-install:${{ matrix.typo3_version }} typo3/cms-recordlist:${{ matrix.typo3_version }} typo3/cms-lowlevel:${{ matrix.typo3_version }} typo3/cms-about:${{ matrix.typo3_version }} typo3/cms-belog:${{ matrix.typo3_version }} typo3/cms-beuser:${{ matrix.typo3_version }} typo3/cms-felogin:${{ matrix.typo3_version }} typo3/cms-fluid-styled-content:${{ matrix.typo3_version }} typo3/cms-form:${{ matrix.typo3_version }} typo3/cms-impexp:${{ matrix.typo3_version }} typo3/cms-info:${{ matrix.typo3_version }} typo3/cms-rte-ckeditor:${{ matrix.typo3_version }} typo3/cms-setup:${{ matrix.typo3_version }} typo3/cms-seo:${{ matrix.typo3_version }} typo3/cms-sys-note:${{ matrix.typo3_version }} typo3/cms-t3editor:${{ matrix.typo3_version }} typo3/cms-tstemplate:${{ matrix.typo3_version }} typo3/cms-viewpage:${{ matrix.typo3_version }} typo3/cms-adminpanel:${{ matrix.typo3_version }} typo3/cms-redirects:${{ matrix.typo3_version }} typo3/cms-workspaces:${{ matrix.typo3_version }} typo3/cms-reports:${{ matrix.typo3_version }} typo3/cms-scheduler:${{ matrix.typo3_version }} typo3/cms-recycler:${{ matrix.typo3_version }} typo3/cms-opendocs:${{ matrix.typo3_version }} typo3/cms-linkvalidator:${{ matrix.typo3_version }}

      - name: Unit tests
        run: .Build/bin/phpunit --colors -c phpunit.xml
