name: Coding Style

on:
  push:
    branches: [ "master" ]
  pull_request: ~

jobs:
  ci:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3
      - name: Set up PHP Version
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.2
          tools: composer:v1
      - name: Validate composer.json
        run: composer validate --strict
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: .Build/vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-php-latest
      - name: Install dependencies
        run: composer install
      - name: ECS
        run: .Build/bin/ecs
